// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/footer.tsx";
import * as $1 from "./routes/api/header.tsx";
import * as $2 from "./routes/api/hero.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/api/layout.tsx";
import * as $5 from "./routes/api/microcmsClient.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/works/[id].tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/api/footer.tsx": $0,
    "./routes/api/header.tsx": $1,
    "./routes/api/hero.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/api/layout.tsx": $4,
    "./routes/api/microcmsClient.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/works/[id].tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
